import socket
server=socke.socket(socket.AF_INET,socket.SOCK_STREAM)
hostname=socket.gethostname()
sever.bind((hostname,8080))
sever.listen(5)
client,addr=sever.accept()
res=client.recv(1024)
print(res.upper())
client.close()
sever.close()
